//! Active NBA Teams based on https://www.basketball-reference.com/teams/
const nbaTeams = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "Las Vegas",
    "Los Angeles Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlanda Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Seattle SuperSonics",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
];

//! ABA+Old Teams based on https://www.basketball-reference.com/teams/
const oldNBATeams = [
    "St. Louis Hawks",
    "Milwaukee Hawks",
    "Tri-Cities Blackhawks",
    "New Jersey Nets",
    "New York Nets",
    "New Jersey Americans",
    "Charlotte Bobcats",
    "Charlotte Hornets",
    "Denver Rockets",
    "Fort Wayne Pistons",
    "San Fransico Warriors",
    "Philadelphia Warriors",
    "San Diego Rockets",
    "San Diego Clippers",
    "Buffalo Braves",
    "Minneapolis Lakers",
    "Vancouver Grizzlies",
    "NO/Ok. City Hornets",
    "New Orleans Hornets",
    "Syracuse Nationals",
    "Kansas City Kings",
    "Kansas City-Omaha Kings",
    "Cincinnati Royals",
    "Rochester Royals",
    "Texas Chaparrals",
    "Dallas Chaparrals",
    "New Orleans Jazz",
    "Washington Bullets",
    "Capital Bullets",
    "Baltimate Bullets",
    "Chicago Zephyrs",
    "Chicago Packers"
];

//! WNBA Teams (all-time) based on https://www.basketball-reference.com/wnba/teams/
const WNBATeams = [
    "Atlanta Dream",
    "Chicago Sky",
    "Connecticut Sun",
    "Indiana Fever",
    "Los Angeles Sparks",
    "Minnesota Lynx",
    "New York Liberty",
    "Phoenix Mercuty",
    "Las Vegas Aces",
    "Seattle Storm",
    "Washington Mystics",
    "Dallas Wings",
    "Houston Comet",
    "Sacramento Monarchs",
    "Cleveland Rockers",
    "Miama Sol",
    "Portland Fire",
    "San Diego Storm",
    "Utah Stars",
    "Washington Mystics"
];

//! Defunct NBA Teams based on https://www.basketball-reference.com/teams/
const defunctNBATeams = [
    "Anderson Packers",
    "Baltimore Bullets",
    "Chicago Stags",
    "Cleveland Rebels",
    "Detroit Falcons",
    "Indianapolis Jets",
    "Indianapolist Olympians",
    "Kentucky Colonels",
    "Memphis Sounds",
    "Memphis Tams",
    "Memphis Pros",
    "New Orleans Buccaneers",
    "Pittsburgh Condors",
    "Minnesota Pipers",
    "Pittsburgh Pipers",
    "Pittsburgh Ironmen",
    "Providence Steam Rollers",
    "San Diego Sails",
    "San Diego Conquistadors",
    "Sheboygan Red Skins",
    "Spirits of St. Louis",
    "Carolina Cougars",
    "Houston Mavericks",
    "St. Louis Bombers",
    "The Floridians",
    "Miami Floridians",
    "Minnesota Muskies",
    "Toronto Huskies",
    "Utah Stars",
    "Los Angeles Stars",
    "Anaheim Amigos",
    "Virginia Squires",
    "Oakland Oaks",
    "Washington Capitols",
    "Waterloo Hawks"
];

//! G-Leage Teams Array based on basketball-reference.com
const GLeagueTeams = [
    "Aqua Caliente Clippers",
    "Austin Spurts",
    "Austin Toros",
    "Columbus Riverdragons",
    "Birmingham Squadron",
    "Erie BayHawks",
    "Capital City Go-Go",
    "Ciudad de Mexico Capitanes",
    "Cleveland Charge",
    "Canton Charge",
    "New Mexico Thunderbirds",
    "Albuquerque Thunderbirds",
    "Huntsville Flight",
    "College Park",
    "Erie BayHawks",
    "Delaware Blue Coats",
    "Delaware 87ers",
    "Utah Flash",
    "Fort Wayne Mad Ants",
    "G League Ignite",
    "Grand Rapids Gold",
    "Grand Rapids Drive",
    "Springfield Armo",
    "Anaheim Arsenal",
    "Greensboro Swarm",
    "Iowa Wolves",
    "Franchise",
    "Iowa Energy",
    "Lakeland Magic",
    "Erie BayHawks",
    "Long Island Nets",
    "Maine Celtics",
    "Maine Red Claws",
    "Memphis Hustl",
    "Motor City Cruise",
    "Northern Arizona",
    "Bakersfield Jam",
    "Oklahoma City Blue",
    "Tulsa 66ers",
    "Asheville Altitude",
    "Rio Grande",
    "Salt Lake City Stars",
    "Idaho Stampede",
    "Santa Cruz Warriors",
    "Dakota Wizards",
    "Sioux Falls Skyforce",
    "South Bay Lakers",
    "Los Angeles D-Fenders",
    "Stockton Kings",
    "Reno Bighorns",
    "Texas Legends",
    "Colorado 14ers",
    "Westchester Knicks",
    "Windy City Bulls",
    "Wisconsin Herd"
];

//! NBL Teams Array based on: https://www.basketball-reference.com/nbl/teams/
const nblTeams = [
    "Akron Firestone Non-Skids",
    "Akron Goodyear Wingfoots",
    "Anderson Duffey Packers",
    "Buffalo Bisons",
    "Chicago American Gears",
    "Chicago Studebaker Flyers",
    "Chicago Bruins",
    "Cincinnati Comellos",
    "Cleveland Allmen Transfers",
    "Cleveland Chase Brassmen",
    "Columbus Athletic Supply",
    "Dayton Metropolitans",
    "Dayton Rens",
    "Detroit Eagles",
    "Detroit Gems",
    "Fort Wayne General Electrics",
    "Fort Wayne Zollner Pistons",
    "Hammond Calumet Buccaneers",
    "Hammond Ciesar All-Americans",
    "Whiting Ciesar All-Americans",
    "Indianapolis Kautskys",
    "Kankakee Gallagher Trojans",
    "Milwaukee Lakers",
    "Milwaukee Panthers",
    "Detroit Gems",
    "Oshkosh All-Stars",
    "Pittsburgh Pirates",
    "Pittsburgh Raiders",
    "Rochester Royals",
    "Sheboygan Redskins",
    "Syracuse Nationals",
    "Toledo Jeeps",
    "Toledo Jim White Chevrolets",
    "Tri-Cities Blackhawks",
    "Waterloo Hawks",
    "Youngstown Bears"
];

//! Liga ACB Teams Array               
const ligaACBTeams = [
    "Baloncesto Leon",
    "Basket Zaragoza",
    "BC Andorra",
    "Bilbao Basket",
    "Caceres CB",
    "Cantabria Baloncesto",
    "CB Breogan",
    "CB Cajabilbao",
    "CB Canarias",
    "CB Ciudad de Huelva",
    "CB Collado Villalba",
    "CB Girona",
    "CB Gran Canaria",
    "CB Granada",
    "CB Granollers",
    "CB LHospitalet",
    "CB Lucentum Alicante",
    "CB Maristas Malaga",
    "CB Miraflores",
    "CB Murcia",
    "CB OAR Ferrol",
    "CB Penas Huesca",
    "CB Salamanca",
    "CB Valladolid",
    "CB Zaragoza",
    "CD Cajamadrid",
    "CD Oximesa",
    "CE Lleida Basquet",
    "CEB Lliria",
    "Circol Catolic de Badalona",
    "Club de Baloncesto Askatuak",
    "Estudiantes",
    "FC Barcelona",
    "Fuenlabrada",
    "Gijon Baloncesto",
    "Gipuzkoa Basket",
    "Joventut",
    "Manresa",
    "Menorca Basquet",
    "Obradoiro",
    "Ourense Baloncesto",
    "RCD Espanyol Basquet",
    "Real Madrid",
    "Saski Baskonia",
    "Sevilla",
    "Tenerife AB",
    "Tenerife CB",
    "Unicaja",
    "Valencia"
];

//! CBA Teams Array           
const cbaTeams = [
    "Bayi Rockets",
    "Beijing Ducks",
    "Beikong Fly Dragons",
    "Fujian Sturgeons",
    "Guangdong Southern Tigers",
    "Guangzhou Loong-Lions",
    "Jiangsu Dragons",
    "Jilin Northeast Tigers",
    "Liaoning Flying Leopards",
    "Nanjing Monkey Kings",
    "Qingdao Eagles",
    "Shandong Golden Stars",
    "Shanghai Sharks",
    "Shanxi Loongs",
    "Sichuan Blue Whales",
    "Shenzhen Leopards",
    "Sichuan Blue Whales",
    "Tianjin Gold Lions",
    "Xinjiang Flying Tigers",
    "Zhejiang Golden Bulls",
    "Zhejiang Lions"
];

//! FIBA Teams Array
const fibaTeams = [
    "Angola",
    "Argentina",
    "Australia",
    "Brazil",
    "Canada",
    "China",
    "Croatia",
    "Czech Republic",
    "Dominican Republic",
    "Egypt",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Iran",
    "Italy",
    "Ivory Coast",
    "Japan",
    "Jordan",
    "Korea",
    "Lebanon",
    "Lithuania",
    "Mexico",
    "Montenegro",
    "New Zealand",
    "Nigeria",
    "Philippines",
    "Poland",
    "Puerto Rico",
    "Russia",
    "Senegal",
    "Serbia",
    "Slovenia",
    "Spain",
    "Tunisia",
    "Turkey",
    "Ukraine",
    "United States",
    "Venezuela"
];

//! Men's Olympics Array         
const OlympicTeams = [
    "Angola",
    "Argentina",
    "Australia",
    "Belgium",
    "Brazil",
    "Bulgaria",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "Chinese Taipei",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Czechoslovakia",
    "Egypt",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Great Britain",
    "Greece",
    "Hungary",
    "India",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Japan",
    "Korea",
    "Latvia",
    "Lithuania",
    "Mexico",
    "Morocco",
    "New Zealand",
    "Nigeria",
    "Panama",
    "Peru",
    "Phillipines",
    "Poland",
    "Puerto Rico",
    "Romania",
    "Russia",
    "Senegal",
    "Serbia",
    "Serbia and Montenegro",
    "Singapore",
    "Slovenia",
    "Soviet Union",
    "Spain",
    "Sweden",
    "Switzerland",
    "Thailand",
    "Tunisia",
    "Turkey",
    "United States",
    "Uruguay",
    "Venezuela",
    "West Germany",
    "Yugoslavia"
];


//! Exporting the arrays to be used in other files
// module.exports = {
//     nbaTeams,
//     oldNBATeams,
//     WNBATeams,
//     defunctNBATeams,
//     GLeagueTeams,
//     ligaACBTeams,
//     cbaTeams,
//     fibaTeams,
//     OlympicTeams
// };  //! End of module.exports
